### PR TITLE
new Branding for the SDK!

### PR DESCRIPTION
**Pull request by Pesegato**

### CODE REVIEW

**Comment by grizeldi** [comment]
Nah not worth the undoing work after april fools is over.

**Comment by Pesegato** [comment]
Well is just drag'n'drop on the folder (which you can do right on the web browser) plus 2 click to merge... but I understand if you prefer to spend your time in more productive stuff ;)

**Comment by grizeldi** [comment]
I know that I'm not really experienced in git but as far as I know undoing
stuff with git is quite a mess.

**Comment by Pesegato** [comment]
If you merge my pr and tag the release, I'll make another PR that brings the monkey back. Deal? ;)

**Comment by grizeldi** [comment]
That's up to darkchaos/mefisto. I don't have push permissions for this repo.
But yeah that would be ok IMO.

**Comment by empirephoenix** [comment]
The binary would still be in the repository forevery, still I kinda must resist clicking the merge button XD

**Comment by Pesegato** [comment]
Not only merge, but also tag release... otherwise it is pointless.

**Comment by Pesegato** [comment]
The poll is going strong:

https://hub.jmonkeyengine.org/t/ummm-what-just-happened-to-system-administrator-of-this-website/35517/28?u=pesegato

**Comment by shadowislord** [comment]
Looks good to me 🦄   :+1:  :+1:  :+1: 

### ✔️ Official Management Seal of Approval

**Comment by Pesegato** [comment]
Hopefull this won't deter the merge; however I'll be AFK over the weekend and won't be able to PR the monkey... but hey, let's give the pony a weekend... :monkey_face:

**Comment by grizeldi** [comment]
No worries @Pesegato I think I have the monkey image on my fork. I can make the PR.

**Comment by MeFisto94** [comment]
Just to note that: I was working the whole 1st so I couldn't react to this :( 
Git/CVS is built that way you can easily revert anything which has been done. So you can just undo the PR again (which is what those systems are for).

This has been done by Dokthar already

**Pull request merged**
