### PR TITLE
updates material. null check if mesh names have changed

### PR DESCRIPTION
**Pull request by neph1**
Proposed fix for #314

### CODE REVIEW

**Comment by MeFisto94** [comment]
Looking good to me, but I think we should use Material#clone.
Worst case, we produce some garbage overhead.
I come to that thinking because of, as said in #314, it may be that trying to load the j3o (or even blend/gltf!) again, may have the same Material instance, and if we share a mutable reference, there may be issues where having multiple scene explorers open you can trigger undesired side effects.

Besides that, I have the nit of adding a few more spaces (e.g between `//` and the actual comment and around the if statement)
Also taking the chance on thanking you again for your big efforts on helping out on the SDK :)

**Comment by neph1** [comment]
I agree on using clone. I came to the same conclusion while thinking about the PR. Will amend tonight

Np. Might as well thank you for keeping the SDK alive for so long :)

**Comment by neph1** [comment]
"First sentence of Javadoc is missing an ending period." omfg! Squash please.

**Comment by MeFisto94** [comment]
True, I guess that's what your other PR is set for to do :)

**Pull request merged**
