### PR TITLE
Upgrade SDK to Netbeans 9

### PR DESCRIPTION
**Pull request by MeFisto94**
Title already says it all.
I have created a Pull Request so people can check the changes out and see what was involved.
Also we could squash-merge the branch that way.

### CODE REVIEW

**Comment by grizeldi** [comment]
Not really sure who is going to check out the changes involved and I'm still against squashing. That said, I'll give it a spin. Is the build process still the same?

**Comment by MeFisto94** [comment]
Well squashing because otherwise it'd be "Fix XYZ, Fix XYZ this time for real, XYZ the third". But I am fine with both.
Build process is the same, you only need to delete netbeans and nbproject/platform-properties.private (or how it is called), then it'll redownload netbeans. Oh and invoking gradlew clean doesn't hurt either.

Alternatively just check the repo out again. That's even cleaner

**Comment by rkraneis** [comment]
Should this be updated to current NetBeans LTS (11.0)? 9 was more of an in-between release and 10.0 the first real one from Apache.

**Comment by MeFisto94** [comment]
Yes, netbeans-11 is also available already [here](https://github.com/jMonkeyEngine/sdk/tree/netbeans-11), but I'd first merge netbeans 9 and then 11, instead of skipping two versions at once.

I didn't get feedback as most people don't want to build the SDK, I guess, so I will have to merge this PR for the next release and see what happens. If that goes well, the following release (or maybe just after a month), I'll merge Netbeans 11 then.

**Comment by rkraneis** [comment]
Hmm, so I have some problems testing this PR:
- following `readme.md` I first ran `build_engine.sh` which installed `jme-*-3.3-SNAPSHOT` locally
- the current build wants to build against `jme-*-3.3.0-netbeans-9` which I of course do not have locally
- matching the dependencies in SDK's build.gradle leads to compilation errors:

```
rene@regulus-milkyway ~/P/J/sdk> ./gradlew buildSdk
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Full Version: 3.3-netbeans-9-1895
POM Version: 3.3.0-netbeans-9-SNAPSHOT
NBM Revision: 1895
NBM UC Suffix: netbeans-9-nightly/3.3/plugins

> Task :overrideHarness
> Will patch harness file "app.exe"!
> Will patch harness file "app64.exe"!
> Will patch harness file "pre7_app.exe"!

> Task :buildSdk
[ant:nb-javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[ant:parseprojectxml] The module org.netbeans.modules.java.hints.legacy.spi has been deprecated
[ant:parseprojectxml] The module org.netbeans.modules.java.hints.legacy.spi has been deprecated
[ant:nb-javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:18: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:17: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:20: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/UpdateHint.java:17: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:4: error: package com.sun.source.tree does not exist
[ant:nb-javac] import com.sun.source.tree.Tree;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:5: error: package com.sun.source.tree.Tree does not exist
[ant:nb-javac] import com.sun.source.tree.Tree.Kind;
[ant:nb-javac]                                ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:6: error: package com.sun.source.util does not exist
[ant:nb-javac] import com.sun.source.util.SourcePositions;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:7: error: package com.sun.source.util does not exist
[ant:nb-javac] import com.sun.source.util.TreePath;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:18: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:32: error: package Tree does not exist
[ant:nb-javac]     private static final Set<Tree.Kind> TREE_KINDS =
[ant:nb-javac]                                  ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:42: error: cannot find symbol
[ant:nb-javac]     public Set<Kind> getTreeKinds() {
[ant:nb-javac]                ^
[ant:nb-javac]   symbol:   class Kind
[ant:nb-javac]   location: class InternalMethodHint
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java:47: error: cannot find symbol
[ant:nb-javac]     public List<ErrorDescription> run(CompilationInfo info, TreePath treePath) {
[ant:nb-javac]                                                             ^
[ant:nb-javac]   symbol:   class TreePath
[ant:nb-javac]   location: class InternalMethodHint
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:4: error: package com.sun.source.tree does not exist
[ant:nb-javac] import com.sun.source.tree.Tree;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:6: error: package com.sun.source.util does not exist
[ant:nb-javac] import com.sun.source.util.SourcePositions;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:7: error: package com.sun.source.util does not exist
[ant:nb-javac] import com.sun.source.util.TreePath;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:17: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:31: error: package Tree does not exist
[ant:nb-javac]     private static final Set<Tree.Kind> TREE_KINDS =
[ant:nb-javac]                                  ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:41: error: cannot find symbol
[ant:nb-javac]     public Set<Kind> getTreeKinds() {
[ant:nb-javac]                ^
[ant:nb-javac]   symbol:   class Kind
[ant:nb-javac]   location: class ReadOnlyPrimitiveHint
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java:46: error: cannot find symbol
[ant:nb-javac]     public List<ErrorDescription> run(CompilationInfo info, TreePath treePath) {
[ant:nb-javac]                                                             ^
[ant:nb-javac]   symbol:   class TreePath
[ant:nb-javac]   location: class ReadOnlyPrimitiveHint
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:3: error: package com.sun.source.tree does not exist
[ant:nb-javac] import com.sun.source.tree.MethodTree;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:4: error: package com.sun.source.tree does not exist
[ant:nb-javac] import com.sun.source.tree.StatementTree;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:7: error: package com.sun.source.util does not exist
[ant:nb-javac] import com.sun.source.util.SourcePositions;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:20: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:34: error: package Tree does not exist
[ant:nb-javac]     private static final Set<Tree.Kind> TREE_KINDS =
[ant:nb-javac]                                  ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:45: error: cannot find symbol
[ant:nb-javac]     public Set<Kind> getTreeKinds() {
[ant:nb-javac]                ^
[ant:nb-javac]   symbol:   class Kind
[ant:nb-javac]   location: class TempVarsHint
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:50: error: cannot find symbol
[ant:nb-javac]     public List<ErrorDescription> run(CompilationInfo info, TreePath treePath) {
[ant:nb-javac]                                                             ^
[ant:nb-javac]   symbol:   class TreePath
[ant:nb-javac]   location: class TempVarsHint
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/UpdateHint.java:5: error: package com.sun.source.util does not exist
[ant:nb-javac] import com.sun.source.util.SourcePositions;
[ant:nb-javac]                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/UpdateHint.java:17: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
[ant:nb-javac]                                           ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/UpdateHint.java:31: error: package Tree does not exist
[ant:nb-javac]     private static final Set<Tree.Kind> TREE_KINDS =
[ant:nb-javac]                                  ^
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/UpdateHint.java:41: error: cannot find symbol
[ant:nb-javac]     public Set<Kind> getTreeKinds() {
[ant:nb-javac]                ^
[ant:nb-javac]   symbol:   class Kind
[ant:nb-javac]   location: class UpdateHint
[ant:nb-javac] /home/rene/Projects/JmonkeyEngine/sdk/jme3-code-check/src/com/jme3/gde/codecheck/hints/UpdateHint.java:46: error: cannot find symbol
[ant:nb-javac]     public List<ErrorDescription> run(CompilationInfo info, TreePath treePath) {
[ant:nb-javac]                                                             ^
[ant:nb-javac]   symbol:   class TreePath
[ant:nb-javac]   location: class UpdateHint
[ant:nb-javac] 23 errors
[ant:nb-javac] 8 warnings

> Task :buildSdk FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rene/Projects/JmonkeyEngine/sdk/build.gradle' line: 634

* What went wrong:
Execution failed for task ':buildSdk'.
> The following error occurred while executing this line:
  /home/rene/Projects/JmonkeyEngine/sdk/netbeans/harness/suite.xml:163: The following error occurred while executing this line:
  /home/rene/Projects/JmonkeyEngine/sdk/netbeans/harness/common.xml:201: Compile failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
8 actionable tasks: 8 executed
```
A cursory look seems to imply that I'm missing tools.jar on the classpath but I don't find any mention of that in either `.travis.yml`, `readme.md` or `doc/*`.

**Comment by MeFisto94** [comment]
I think the version mismatch is due to #212, because the engine has changed the versioning scheme.
The catch here is that you build with java 8, I assume, and that won't work here. Look at .travis.yml, there is a special engine version required. I think I couldn't go too high, because then we had problems with missing JAXB dependents etc.

**Comment by MeFisto94** [comment]
The Test period has been long enough. Sadly we didn't receive any/much feedback, but since 3.3-beta1 is out, we'll use this as beta-testing for the SDK as well.

**Pull request merged**
