### PR TITLE
include libraries: Heart v6.0.0, Minie v3.0.0, Wes v0.6.0

### PR DESCRIPTION
**Pull request by stephengold**

### CODE REVIEW

**Comment by MeFisto94** [comment]
Thanks for caring about the SDK! :)

**Comment by stephengold** [comment]
I'm curious: what are your intentions regarding the SDK? What should I tell users and potential users?

**Comment by MeFisto94** [comment]
I really want to release a 3.3 version, but there are a few fundamental changes that haven't been really tested and I'd want to move to a working update center again, so that's a bit "critical" to just release, which is why I'd need testing, but there aren't many available that would care about testing.

For instance, I've hacked 3.3 Animation System support in, but we have yet to see if there are more bugs than only #252. 
And the update system together with maybe cutting out modules like nifty to be not part of the standard distribution, requires even more testing, of course. But it could help us with future updates.

Maybe I should just do a testing build and see what happens

**Comment by stephengold** [comment]
If there's a build you want tested, I'll install and test it. However, I might not test it very thoroughly.

**Pull request merged**
