### PR TITLE
Replace icons

### PR DESCRIPTION
**Pull request by neph1**
A first installment of svg icons for core. Some difficult to find/make are still left. Each module then has its own set of icons, usually just a few. I've tried to stick to the theme/look of the old ones, but some liberty has been taken in a few cases.
Would have been nice to keep color and size outside the svg's, but not sure how to do that.

A bunch of empty merge commits refuse to go away. I'll squash this when merging.

#355

### CODE REVIEW

**Comment by tonihele** [comment]
Cool cool. The licensing part is ok?

**Comment by tonihele** [comment]
> Cool cool. The licensing part is ok?

Ah on the javadoc. Yeah, looks to satisfy the requirements I suppose.

**Comment by neph1** [comment]
I think we can probably put it somewhere more visible too. There seems to be some credits on the About page already, so maybe there. I don't know if we need to be more specific, though, like iconX by authorY.

**Comment by tonihele** [comment]
> I think we can probably put it somewhere more visible too. There seems to be some credits on the About page already, so maybe there. I don't know if we need to be more specific, though, like iconX by authorY.

Good idea, I don't think we need to be more specific.

**Comment by neph1** [comment]
That should conclude SceneComposer and SceneViewer. I tried to get a more coherent look on the icons and also made them larger, since displays have higher resolution than 640x480 nowadays.
Screenshot from 2022-09-28 20-03-13

**Comment by neph1** [comment]
Unlike the bitmaps, the look and feel actually changes the colors of the svg. I had not anticipated that (but it is in essence a good thing?). I had unfortunately tested the colors on the vanilla look and feel, and not dark metal. The blue and yellow look ok, I think, but the green is a bit too saturated. I better retweak the colors.

**Comment by neph1** [comment]
Hmm, I just updated all the colors to look better with the chosen LAF (sed ftw), but I see now that I did have a dark theme in the first screenshot too. I can't select DarkMonkey in the list. Not sure how to proceed.
On a sidenote, I just checked out DarkLaF in the list. A superior LaF imho. Not "compatible" with the color change, though. Is it only DarkMetal that distorts the colors? Because all the others seem to show them as they were intended.

**Pull request merged**
