### PR TITLE
making the cursor arrow more usable, show position in panel.

### PR DESCRIPTION
**Pull request by neph1**
Might seem like a minor thing, but sometimes you want to position things in code and currently you need to create a new Node and drag it around until it's where you want it. Now you can just point wherever and see the position.

### CODE REVIEW

**Comment by MeFisto94** [comment]
It feels we really need to do some taming on Codacy and sadly the inline comments it does make no sense at all

**Comment by neph1** [comment]
Most of the issues here are due to the NB generated UI code.

**Comment by tonihele** [comment]
Hmm, point how? I'm trying this out but it always displays:
image

**Comment by neph1** [comment]
"Works on my machine"

Hmm. Just to make sure; You're not clicking on the void? I'll see if I can find out something

**Comment by tonihele** [comment]
Here is how I tried it, did I misunderstood how this should work:
https://www.youtube.com/watch?v=SPYq5kRwqLw

**Comment by tonihele** [comment]
Ah okay, it does work. Invalid user error. You are supposed to click on a mesh to position the cursor... Okay okay okay, it works :)

**Comment by tonihele** [comment]
Thank you for the contribution!

**Pull request merged**
