### PR TITLE
#264 Removal of ogrexml. Unsure of whether I've caught everything, bu…

### PR DESCRIPTION
**Pull request by neph1**
…t it builds and loads. #264 
I haven't tested this extensively, just checked that the SDK  builds and loads. Anything particular?

### CODE REVIEW

**Comment by MeFisto94** [comment]
I guess I am also targetting it for 3.5, which should be available "soon" :D (As soon as 3.4 is working, that is)

**Comment by tonihele** [comment]
@MeFisto94  care to check this one?

**Review by MeFisto94 — COMMENTED** [review]
Looks good, the only thing I am uncertain is/are the asset packs then.
Do we need to remove them, if there is no real use for them anymore?
Like isn't this world forge the only real implementation/use case?

**Comment by neph1** [comment]
I thought AssetPacks were a generic implementation to distribute collections of assets? Just that noone ever used them.

**Comment by MeFisto94** [comment]
True, I guess it's just the other way around: world forge was one of the reasons we had ogre import, I guess.
and yeah, makes sense to keep asset packs, maybe someday someone finds them useful

**Pull request merged**
