### PR TITLE
adding black outline on icons. removing label from "play" button

### PR DESCRIPTION
**Pull request by neph1**

### CODE REVIEW

**Comment by tonihele** [comment]
Definitely more readable now. I found few icons that didn't scale:
image

**Comment by tonihele** [comment]
The _pause_ also looks little bit.... restless... looks like it is too big:
image

**Comment by neph1** [comment]
Looks like the terrain icon and node icon didn't get outlines either. I used "sed" to replace the styles and had to manually fix some of them.

**Comment by neph1** [comment]
image

Redesigned the node icon a bit to make it more distinct. Replaced the waypoint icon with something more suitable.
Light bulb color is corrected, too (after this screenshot).

**Pull request merged**
