### PR TITLE
Fixed the scene editor control problem

### PR DESCRIPTION
**Pull request by grizeldi**
Mitigated the problem described in issue #10. The solution works for classes outside the superclass' package.
It doesn't fix the whole issue but until I find a better solution it should be better than nothing.

### CODE REVIEW

**Comment by grizeldi** [comment]
FIXED IT!!! :grinning: 
It took me a while to figure it out but now it displays all children that implement/extend Control/AbstractControl.

**Comment by MeFisto94** [comment]
I'll look into it tomorrow after my exam.
Thank you for your work so far :) 

The old PR had the issue that you could have edge cases taking multiple iterations when the order of the classes was wrong.

**Comment by grizeldi** [comment]
Hehe learning for an exam here too ;)

**Comment by MeFisto94** [comment]
Well this still has the same problem:
When you have the following order:
`A extends B; B extends Control` however the list looks like this: `A, B`. Then it will process A but the list doesn't have B yet. Then it goes to B where it notices that B has a Control..

However I'll implement something based on it :)

**Comment by grizeldi** [comment]
Darn, didn't think of that... I'll try to fix it if you won't be faster.

**Comment by grizeldi** [comment]
But I can't think of a way without recursion... :(

**Comment by MeFisto94** [comment]
Note that every recursion can be turned into a loop (and this is basically what my fix does).
Also Note that you didn't take care of the interfaces in your case.

But thanks for the effort anyway and good luck with your exam :)

**Pull request closed without merging**
