### PR TITLE
Include the test data

### LINKED ISSUE #266: Showing HDR Environment is broken
```
com.jme3.asset.AssetNotFoundException: Textures/Sky/Path.hdr (Flipped)
    at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:382)
    at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:404)
    at com.jme3.util.SkyFactory.createSky(SkyFactory.java:291)
    at com.jme3.gde.core.scene.SceneApplication$11.run(SceneApplication.java:640)
```

I wonder how this could happen, given that I just added this feature very recently.
The file should stem from testdata.

### PR DESCRIPTION
**Pull request by tonihele**
Resolves #266

### CODE REVIEW

**Comment by tonihele** [comment]
Blah, seems that this works one time only. The real solution is to do this in Gradle, like the others....

**Comment by tonihele** [comment]
Doesn't work... Needs investigation...

**Comment by neph1** [comment]
I took a look at this issue using this PR as a base. I didn't get very far, but I did notice that the jme3-project-testdata path doesn't use the more common "release/modules/ext/", but rather "release/libs". Not sure if it means anything, and didn't work even though I changed it. :shrug:

**Comment by neph1** [comment]
Maybe I'm misunderstanding things, but I think it actually works.
image

The lib just needs to be moved like in my comment above (to match the xml)

**Pull request closed without merging**
