### PR TITLE
add 5 optional libraries from com.simsilica

### PR DESCRIPTION
**Pull request by stephengold**
To help steer users toward Paul Speed's libraries.

### CODE REVIEW

**Comment by tonihele** [comment]
I think these will only come to the Ant projects as selectable. Is that the goal?

**Comment by stephengold** [comment]
The goal is to make these libraries as accessible as possible to SDK users. Toward this end, if there's something we could do for Gradle and Maven users, that'd be great.

**Comment by tonihele** [comment]
Did you try the wizard:
image

**Comment by stephengold** [comment]
not recently

I thought this build.gradle was how 3rd-party libraries (like Wes) were bundled into the SDK for inclusion in user projects. If I was mistaken, then please close this PR without integrating.

**Comment by tonihele** [comment]
No, it is probably fine. Im just trying to make sure what you want to do gets done. This way they go to Ant projects only, then the user has to be smart enough to figure out how to add them to their project.

The Gradle is recommended format. And there is the Gradle wizard which lets the user select all the libraries he/she/it/they/them/apache helicopter is interested in. The selection of packages is here: https://github.com/jMonkeyEngine/sdk/blob/master/jme3-templates/src/com/jme3/gde/templates/gradledesktop/options/AdditionalLibrary.java

**Comment by stephengold** [comment]
> The selection of packages is here

Good to know. Thanks!

**Review by tonihele — APPROVED** [review]

**Pull request merged**
